
name: CI

on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Get Artifacts
        uses: fjogeleit/http-request-action@v1
        id: artifacts
        with:
          url: 'https://api.eu.cloud.talend.com/tmc/v2.6/artifacts?name=FIRST_JOB'
          method: 'GET'
          bearerToken: igoZ4tK3R_2Hzf1Zj0XSkecbHPchWMEJzKILHp0n6EFKOJvDWj86SqOJnId8nyYi
          customHeaders: '{"Content-Type": "application/json"}'
      - name: Get Tasks
        uses: fjogeleit/http-request-action@v1
        id: tasks
        with:
          url: 'https://api.eu.cloud.talend.com/tmc/v2.6/executables/tasks?artifactId=${{fromJson( steps.artifacts.outputs.response).items[0].id }}'
          method: 'GET'
          bearerToken: igoZ4tK3R_2Hzf1Zj0XSkecbHPchWMEJzKILHp0n6EFKOJvDWj86SqOJnId8nyYi
          customHeaders: '{"Content-Type": "application/json"}'
      - name: executable
        run: echo  "${{fromJson( steps.tasks.outputs.response).items[0].executable }}"
      - name: task name 
        id: task_name
        run: |
          input_string="third_job"
          task_name="$input_string ${{fromJson( steps.tasks.outputs.response).items[0].executable }} task"
          echo "::set-output name=task_name::$task_name"
        shell: bash
      - name: test name 
        run: echo   "${{ steps.task_name.outputs.task_name }}"
          

    
   

      
      # - name: Get DEV to UAT promotion
      #   uses: fjogeleit/http-request-action@v1
      #   id: promotion
      #   with:
      #     url: 'https://api.eu.cloud.talend.com/tmc/v2.6/executables/promotions?_s=name%3D%3Ddev%20to%20uat*'
      #     method: 'GET'
      #     bearerToken: igoZ4tK3R_2Hzf1Zj0XSkecbHPchWMEJzKILHp0n6EFKOJvDWj86SqOJnId8nyYi
      #     customHeaders: '{"Content-Type": "application/json"}'
      # - name: test
      #   run : echo "${{fromJson( steps.promotion.outputs.response)[0].executable }}"
      # - name: Execute promotion
      #   uses: fjogeleit/http-request-action@v1
      #   id: execute
      #   with:
      #     url: 'https://api.eu.cloud.talend.com/tmc/v2.6/executions/promotions'
      #     method: 'POST'
      #     bearerToken: igoZ4tK3R_2Hzf1Zj0XSkecbHPchWMEJzKILHp0n6EFKOJvDWj86SqOJnId8nyYi
      #     customHeaders: '{"Content-Type": "application/json"}'
      #     data: '{"executable": "${{fromJson( steps.promotion.outputs.response)[0].executable }}", "keepTargetResources": true, "advanced": { "artifactId": "641993436419bf66f086aaea", "artifactType": "ACTION" }}'
  
      # - name: Get DEV environment
      #   uses: fjogeleit/http-request-action@v1
      #   id: dev
      #   with:
      #     url: 'https://api.eu.cloud.talend.com/tmc/v2.6/environments?query=name%3D%3Ddev'
      #     method: 'GET'
      #     bearerToken: igoZ4tK3R_2Hzf1Zj0XSkecbHPchWMEJzKILHp0n6EFKOJvDWj86SqOJnId8nyYi
      #     customHeaders: '{"Content-Type": "application/json"}'
      # - name: Get Artifacts
      #   uses: fjogeleit/http-request-action@v1
      #   id: artifacts
      #   with:
      #     url: 'https://api.eu.cloud.talend.com/tmc/v2.6/artifacts?name=${{ matrix.word }}&environmentId=${{fromJson( steps.dev.outputs.response)[0].id }}'
      #     method: 'GET'
      #     bearerToken: igoZ4tK3R_2Hzf1Zj0XSkecbHPchWMEJzKILHp0n6EFKOJvDWj86SqOJnId8nyYi
      #     customHeaders: '{"Content-Type": "application/json"}'
